name: Build Spotify Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update && sudo apt install libfuse2
        wget https://raw.githubusercontent.com/edgerunning/Spotify-appimage/main/spotify
        chmod a+x ./spotify
        sudo ./spotify
        mkdir dist
        VERSION=$(wget -q http://repository.spotify.com/pool/non-free/s/spotify-client/ -O - | grep spotify-client_ | grep amd64.deb | grep -o -P '(?<=").*(?=")' | tail -1)
        mv *AppImage dist/Spotify-$VERSION-x86_64.AppImage
    - uses: gautamkrishnar/keepalive-workflow@v1
      with:
        gh_token: ${{ secrets.GH_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Spotify-x86_64.AppImage
        path: 'dist'
        
  
